type Author {
  id: ID!
  name: String!
  todos: [Todo]!
}

type Todo {
  id: ID!
  author: Author
  text: String!
  completed: Boolean!
}

type TodoMutation {
  create(text: String!): Todo!
  complete(id: ID!): Todo!
  remove(id: ID!): ID
}

type Query {
  me: Author!
  author(id: ID): Author!
  authors: [Author]!
  todos: [Todo]!
  todo(id: ID): Todo
}

type Mutation {
  todos: TodoMutation!
}
