"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var root_1 = require("./root");
exports.bootstrapGrapp = root_1.bootstrapGrapp;
var data_fields_1 = require("./data_fields");
exports.Data = data_fields_1.Data;
exports.DataArray = data_fields_1.DataArray;
var db_1 = require("./db");
exports.Db = db_1.Db;
var di_1 = require("./di");
exports.Collection = di_1.Collection;
exports.CreateDoc = di_1.CreateDoc;
exports.Inject = di_1.Inject;
exports.Payload = di_1.Payload;
exports.RemoveDoc = di_1.RemoveDoc;
exports.Typer = di_1.Typer;
exports.UpdateDoc = di_1.UpdateDoc;
var doc_1 = require("./doc");
exports.Doc = doc_1.decorateDoc;
exports.DocQuery = doc_1.decorateDocOpe;
exports.DocMutation = doc_1.decorateDocOpe;
var grapp_1 = require("./grapp");
exports.Grapp = grapp_1.decorateGrapp;
var type_1 = require("./type");
exports.Type = type_1.decorateType;
var relation_fields_1 = require("./relation_fields");
exports.Relation = relation_fields_1.Relation;
//# sourceMappingURL=index.js.map